### ISSUE TITLE
NoClassDefFoundError: com/contentful/vault/ContentType after upgrading to Android Studio 3.0 Canary 3

### ISSUE THREAD

**Issue by kzotin** [contentful/vault#122]
Hi, 
After upgrading to Android Studio 3.0 Canary 3 and migrating everything according to the guide, project fails to build and shows
`NoClassDefFoundError: com/contentful/vault/ContentType `

My build.gradle contains: 
```
    buildToolsVersion "26.0.0-rc2"
...
    implementation 'com.contentful.vault:core:2.1.0'
    annotationProcessor 'com.contentful.vault:compiler:2.1.0'
    
    implementation 'com.squareup.okhttp:okhttp:2.3.0'
    implementation 'com.squareup.okhttp:okhttp-urlconnection:2.3.0'
... 
    // ButterKnife compiles well
    implementation 'com.jakewharton:butterknife:8.6.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.6.0'
```

Thanks in advance.

**Comment by kzotin** [comment]
Proguard and minification are disabled.

**Comment by kzotin** [comment]
Issue is also reproduced with AS 2.4 Preview7

**Comment by mariobodemann** [comment]
Hey,

thanks for reaching out. I will take a look as soon as time and workload permits, but sadly supporting canary and beta versions is not the highest priority right now.

Greetings, and thank you for reporting, 
Mario

**Comment by kzotin** [comment]
Thanks. 
Issue seems to be related to Gradle 3.4+ upgrade.

**Comment by kzotin** [comment]
Still not working with Android Studio 3.0 Canary 6.
This issue blocks migration to such a pleasant tooling update......

**Comment by mariobodemann** [comment]
Hey,

a quick analysis: I found that the new build system does not work with the current available annotation processor. I will try and figure out an alternative/mitigation, but sadly I cannot commit to any timeline just now...

So hang in tight ... ;)

**Comment by mariobodemann** [comment]
@kzotin I did find an answer, which was astonishingly easy: 

Following [the official migration guide to the gradle plugin 3.0](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html) you also need to specify the dependency of the annotation processor with `annotationProcessor`.

This means additionally to you writing 

```
annotationProcessor 'com.contentful.vault:compiler:2.1.0
```

you would need to specify also the `core`:

```
annotationProcessor 'com.contentful.vault:core:2.1.0
annotationProcessor 'com.contentful.vault:compiler:2.1.0
```

(replacing `apt` with `annotationProcessor` is a given I guess ...) I'll add this to the readme of the upcomming 8.0.0 release and will close this issue for now ...
